# Generated by Django 6.1 on 2026-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('tipo_equipo', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('monitor', 'Monitor'), ('impresora', 'Impresora'), ('servidor', 'Servidor'), ('otro', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En uso'), ('en_reparacion', 'En reparación'), ('dado_de_baja', 'Dado de baja')], default='disponible', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
